server.port=8087
spring.application.name=soa-service

# Oracle Database Connection Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle-db:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ba0352}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ba0352pwd}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
