-- Schema Definition for History Service (histdb)
-- IBM DB2 dialect

-- Drop table if exists (uncomment if recreating)
-- DROP TABLE history_records;

CREATE TABLE history_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);
