-- Schema Definition for Report Service (Oracle DB)
-- Oracle Dialect

-- Drop table if exists (uncomment if recreating)
-- DROP TABLE report_records;

CREATE TABLE report_records (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    generated_at TIMESTAMP NOT NULL
);
